# SageMaker Configuration

per_execution_timeout: 86400

# Data Perception
max_file_group_size_to_show: 5
num_example_files_to_show: 1

max_chars_per_file: 768
num_tutorial_retrievals: 30
max_num_tutorials: 5
max_user_input_length: 2048
max_error_message_length: 2048
max_tutorial_length: 32768
create_venv: false
condense_tutorials: True
use_tutorial_summary: True
continuous_improvement: False
optimize_system_resources: False
cleanup_unused_env: True
enable_meta_prompting: False

llm: &default_llm
  provider: anthropic
  model: claude-sonnet-4-20250514
  max_tokens: 65535
  proxy_url: null
  temperature: 0.1
  top_p: 0.9
  verbose: True
  multi_turn: False
  template: null
  add_coding_format_instruction: false
  apply_meta_prompting: False

# Ensure all agent types inherit the SageMaker LLM config
python_coder:
  <<: *default_llm  # Merge llm_config
  multi_turn: True
  apply_meta_prompting: True

bash_coder:
  <<: *default_llm  # Merge llm_config
  multi_turn: True

executer:
  <<: *default_llm  # Merge llm_config
  max_stdout_length: 8192
  max_stderr_length: 2048

meta_prompting:
  <<: *default_llm  # Merge llm_config
  multi_turn: False

reader:
  <<: *default_llm  # Merge llm_config
  details: False

error_analyzer:
  <<: *default_llm  # Merge llm_config

retriever:
  <<: *default_llm  # Merge llm_config

reranker:
  <<: *default_llm  # Merge llm_config
  temperature: 0.
  top_p: 1.

description_file_retriever:
  <<: *default_llm  # Merge llm_config
  temperature: 0.
  top_p: 1.

task_descriptor:
  <<: *default_llm  # Merge llm_config
  max_description_files_length_to_show: 1024
  max_description_files_length_for_summarization: 16384
  apply_meta_prompting: True

tool_selector:
  <<: *default_llm  # Merge llm_config
  temperature: 0.
  top_p: 1.
